# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: besmarts/doc/conf.py

submodules:
  include:
    - besmarts
  recursive: true

python:
  install:
    - requirements: besmarts/doc/requirements.txt
    - method: pip
      path: besmarts/besmarts-core/python
    - method: pip
      path: besmarts/besmarts-rdkit/python
    - method: pip
      path: besmarts/besmarts-mechanics/python
    - method: pip
      path: besmarts/besmarts-scipy/python
    - method: pip
      path: besmarts/besmarts-openmm/python


